# 1- Veri Önişleme

In [2]:
# 1- import library
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# 2- import dataset
dataset = pd.read_csv("./dataset.csv")
print("DATASET\n", dataset)

DATASET
    ulke  boy  kilo   yas cinsiyet
0    tr  130    30  10.0        e
1    tr  125    36  11.0        e
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
4    tr  129    38  12.0        e
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55  27.0        k
11   us  155    50  44.0        k
12   us  160    58   NaN        k
13   us  162    59  41.0        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90   NaN        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k


In [4]:
height = dataset[["boy"]]
print(height)

heightAndWeight = dataset[["boy", "kilo"]]
print(heightAndWeight)

    boy
0   130
1   125
2   135
3   133
4   129
5   180
6   190
7   175
8   177
9   185
10  165
11  155
12  160
13  162
14  167
15  174
16  193
17  187
18  183
19  159
20  164
21  166
    boy  kilo
0   130    30
1   125    36
2   135    34
3   133    30
4   129    38
5   180    90
6   190    80
7   175    90
8   177    60
9   185   105
10  165    55
11  155    50
12  160    58
13  162    59
14  167    62
15  174    70
16  193    90
17  187    80
18  183    88
19  159    40
20  164    66
21  166    56


In [5]:
# 3- Missing Values (Eksik Veriler) 
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")

#integer location = iloc
age = dataset.iloc[:,1:4].values 
print(age)

# fit() fonksiyonu ile öğrenilecek olan değer (strategy) alınır. 
imputer = imputer.fit(age[:,1:4])
# transform ile öğrendiğin değeri, ilgili yere koy 
age[:,1:4] = imputer.transform(age[:,1:4])
print(age)

ageDataFrame = pd.DataFrame(data=age, index=range(len(age)), columns=["Height", "Weight", "Age"])
print(ageDataFrame)

[[130.  30.  10.]
 [125.  36.  11.]
 [135.  34.  10.]
 [133.  30.   9.]
 [129.  38.  12.]
 [180.  90.  30.]
 [190.  80.  25.]
 [175.  90.  35.]
 [177.  60.  22.]
 [185. 105.  33.]
 [165.  55.  27.]
 [155.  50.  44.]
 [160.  58.  nan]
 [162.  59.  41.]
 [167.  62.  55.]
 [174.  70.  47.]
 [193.  90.  nan]
 [187.  80.  27.]
 [183.  88.  28.]
 [159.  40.  29.]
 [164.  66.  32.]
 [166.  56.  42.]]
[[130.    30.    10.  ]
 [125.    36.    11.  ]
 [135.    34.    10.  ]
 [133.    30.     9.  ]
 [129.    38.    12.  ]
 [180.    90.    30.  ]
 [190.    80.    25.  ]
 [175.    90.    35.  ]
 [177.    60.    22.  ]
 [185.   105.    33.  ]
 [165.    55.    27.  ]
 [155.    50.    44.  ]
 [160.    58.    28.45]
 [162.    59.    41.  ]
 [167.    62.    55.  ]
 [174.    70.    47.  ]
 [193.    90.    28.45]
 [187.    80.    27.  ]
 [183.    88.    28.  ]
 [159.    40.    29.  ]
 [164.    66.    32.  ]
 [166.    56.    42.  ]]
    Height  Weight    Age
0    130.0    30.0  10.00
1    125.0    36.0  11

In [6]:
# 4- Encoder : From Categorical Values to Numeric Values
country = dataset.iloc[:,0:1]
print(country)

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# OneHotEncoder'ı bir ColumnTransformer içinde kullan
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [0])],
    remainder='passthrough'
)

country = ct.fit_transform(country)
print(country)

countryDataFrame = pd.DataFrame(data=country, index=range(len(country)), columns=["FR", "TR", "US"])
print(countryDataFrame)

   ulke
0    tr
1    tr
2    tr
3    tr
4    tr
5    tr
6    tr
7    tr
8    tr
9    us
10   us
11   us
12   us
13   us
14   us
15   fr
16   fr
17   fr
18   fr
19   fr
20   fr
21   fr
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
     FR   TR   US
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0


In [7]:
# 5- Dizilerden DataFrame Oluşturulması ve Verilerin Birleştirilmes
sex = dataset.iloc[:,-1].values
print(sex)

# "Sex" sütunundaki değerleri değiştirme
sex = np.where(sex == 'e', 'M', 'F')
print(sex)

sexDataFrame = pd.DataFrame(data=sex, index=range(len(sex)), columns=["Sex"])
print(sexDataFrame)

['e' 'e' 'k' 'k' 'e' 'e' 'e' 'e' 'k' 'e' 'k' 'k' 'k' 'k' 'k' 'e' 'e' 'e'
 'e' 'k' 'k' 'k']
['M' 'M' 'F' 'F' 'M' 'M' 'M' 'M' 'F' 'M' 'F' 'F' 'F' 'F' 'F' 'M' 'M' 'M'
 'M' 'F' 'F' 'F']
   Sex
0    M
1    M
2    F
3    F
4    M
5    M
6    M
7    M
8    F
9    M
10   F
11   F
12   F
13   F
14   F
15   M
16   M
17   M
18   M
19   F
20   F
21   F


In [8]:
# Merge DataFrames
updatedDataset = pd.concat([countryDataFrame, ageDataFrame, sexDataFrame], axis=1) # satırları yan yana ekleme
print(updatedDataset)

dataFrame = pd.concat([countryDataFrame, ageDataFrame], axis=1) 
print(dataFrame)

     FR   TR   US  Height  Weight    Age Sex
0   0.0  1.0  0.0   130.0    30.0  10.00   M
1   0.0  1.0  0.0   125.0    36.0  11.00   M
2   0.0  1.0  0.0   135.0    34.0  10.00   F
3   0.0  1.0  0.0   133.0    30.0   9.00   F
4   0.0  1.0  0.0   129.0    38.0  12.00   M
5   0.0  1.0  0.0   180.0    90.0  30.00   M
6   0.0  1.0  0.0   190.0    80.0  25.00   M
7   0.0  1.0  0.0   175.0    90.0  35.00   M
8   0.0  1.0  0.0   177.0    60.0  22.00   F
9   0.0  0.0  1.0   185.0   105.0  33.00   M
10  0.0  0.0  1.0   165.0    55.0  27.00   F
11  0.0  0.0  1.0   155.0    50.0  44.00   F
12  0.0  0.0  1.0   160.0    58.0  28.45   F
13  0.0  0.0  1.0   162.0    59.0  41.00   F
14  0.0  0.0  1.0   167.0    62.0  55.00   F
15  1.0  0.0  0.0   174.0    70.0  47.00   M
16  1.0  0.0  0.0   193.0    90.0  28.45   M
17  1.0  0.0  0.0   187.0    80.0  27.00   M
18  1.0  0.0  0.0   183.0    88.0  28.00   M
19  1.0  0.0  0.0   159.0    40.0  29.00   F
20  1.0  0.0  0.0   164.0    66.0  32.00   F
21  1.0  0

In [9]:
# 6- Verisetinin Eğitim ve Test Verilerine Bölünmesi
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(dataFrame, sexDataFrame, test_size=0.33, random_state=0)
# Eğitim veri setini ve test veri setini yazdır
print("Training Data:")
print(x_train)
print(y_train)

print("\nTesting Data:")
print(x_test)
print(y_test)

Training Data:
     FR   TR   US  Height  Weight    Age
8   0.0  1.0  0.0   177.0    60.0  22.00
6   0.0  1.0  0.0   190.0    80.0  25.00
16  1.0  0.0  0.0   193.0    90.0  28.45
4   0.0  1.0  0.0   129.0    38.0  12.00
2   0.0  1.0  0.0   135.0    34.0  10.00
5   0.0  1.0  0.0   180.0    90.0  30.00
17  1.0  0.0  0.0   187.0    80.0  27.00
9   0.0  0.0  1.0   185.0   105.0  33.00
7   0.0  1.0  0.0   175.0    90.0  35.00
18  1.0  0.0  0.0   183.0    88.0  28.00
3   0.0  1.0  0.0   133.0    30.0   9.00
0   0.0  1.0  0.0   130.0    30.0  10.00
15  1.0  0.0  0.0   174.0    70.0  47.00
12  0.0  0.0  1.0   160.0    58.0  28.45
   Sex
8    F
6    M
16   M
4    M
2    F
5    M
17   M
9    M
7    M
18   M
3    F
0    M
15   M
12   F

Testing Data:
     FR   TR   US  Height  Weight   Age
20  1.0  0.0  0.0   164.0    66.0  32.0
10  0.0  0.0  1.0   165.0    55.0  27.0
14  0.0  0.0  1.0   167.0    62.0  55.0
13  0.0  0.0  1.0   162.0    59.0  41.0
1   0.0  1.0  0.0   125.0    36.0  11.0
21  1.0  0

In [10]:
# 7- Öznitelik Ölçekleme
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

print("X Training Data:")
print(x_train)
print("\nX Testing Data:")
print(x_test)

X Training Data:
[[-0.63245553  0.8660254  -0.40824829  0.45049444 -0.29657884 -0.24717129]
 [-0.63245553  0.8660254  -0.40824829  1.00824945  0.5096549   0.03416189]
 [ 1.58113883 -1.15470054 -0.40824829  1.13696215  0.91277178  0.35769504]
 [-0.63245553  0.8660254  -0.40824829 -1.6089087  -1.18343596 -1.18494855]
 [-0.63245553  0.8660254  -0.40824829 -1.35148331 -1.34468271 -1.372504  ]
 [-0.63245553  0.8660254  -0.40824829  0.57920713  0.91277178  0.50305051]
 [ 1.58113883 -1.15470054 -0.40824829  0.87953676  0.5096549   0.22171734]
 [-0.63245553 -1.15470054  2.44948974  0.79372829  1.51744708  0.78438369]
 [-0.63245553  0.8660254  -0.40824829  0.36468597  0.91277178  0.97193914]
 [ 1.58113883 -1.15470054 -0.40824829  0.70791983  0.8321484   0.31549506]
 [-0.63245553  0.8660254  -0.40824829 -1.43729177 -1.50592946 -1.46628173]
 [-0.63245553  0.8660254  -0.40824829 -1.56600447 -1.50592946 -1.372504  ]
 [ 1.58113883 -1.15470054 -0.40824829  0.32178174  0.10653803  2.09727185]
 [-0.632